image: gitpod/workspace-full

# Commands to start on workspace startup
tasks:
  - init: npm ci && cargo install wasm-pack
  - command: node tooling/adjust-url.js

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - https://github.com/freeCodeCamp/courses-vscode-extension/releases/download/v3.0.0/freecodecamp-courses-3.0.0.vsix
    - https://github.com/freeCodeCamp/freecodecamp-dark-vscode-theme/releases/download/v1.0.0/freecodecamp-dark-vscode-theme-1.0.0.vsix
