name: "Docker Build"
on:
  push:
    branches-ignore:
      - "renovate/**"
  pull_request:
jobs:
  test:
    name: Dock
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@7dd9e2a3dc350cf687eb1b2a4fadfee8c8e49675 # v3

      - name: Build Dockerfile
        run: |
          docker build -f Dockerfile -t euler-rust .
