name: Linter
on:
  push:
    branches-ignore:
      - "renovate/**"
  pull_request:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Lint Source Files
        run: |
          cd .freeCodeCamp
          npm ci
          npm run lint
